image: "rust:latest"

lint:fmt:
    before_script:
        - rustup component add rustfmt-preview
    script:
        - cargo fmt
        - test $(git ls-files --modified | wc -l) -eq 0 || (echo 'You have introduced some unformated code:'; git ls-files --modified | sed 's/^/* /'; echo 'Please run `cargo fmt` and amend your PR.'; exit 1)

lint:clippy:
    before_script:
        - rustup self update
        - rustup install nightly
        - rustup component add --toolchain=nightly clippy-preview
    script: cargo +nightly clippy -- --deny warnings

test:debug:
    script: cargo test --all-features

test:release:
    script: cargo test --all-features --release
