language: rust

cache: cargo

before_script:
    - rustup component add rustfmt-preview
    - rustup install nightly
    - rustup component add --toolchain=nightly clippy-preview

script:
    - cargo fmt
    - cargo +nightly clippy -- --deny warnings
    - test $(git ls-files --modified | wc -l) -eq 0 || (echo 'You have introduced some unformated code:'; git ls-files --modified | sed 's/^/* /'; echo 'Please run `cargo fmt` and amend your PR.'; exit 1)
    - cargo test --all-features
